### ISSUE TITLE
Lazy-loading not enabled by default?

### ISSUE THREAD

**Issue by mnugter** [SyneticNL/Hyral#45]
Should the lazy-loading decorator be enabled by default? It forces you to do more configuration than you might otherwise need. This should only be required when you know you are going to use this behavior.

**Comment by jurcello** [comment]
I think the lazy-loading decorator should indeed not be enabled by default, because of the configuration you mentioned. I agree with your last sentence.

**Comment by mnugter** [comment]
Opened PR: #53

**Comment by mnugter** [comment]
Moved to 2.0 as it's a BC break

**Comment by mnugter** [comment]
It might need quicker release as it might be the cause of some bugs and the current implementation seems a bit experimental. Therefore tagging as 1.1 and accept a notification on BC break.
